apiVersion: v1
entries:
  ohdsi:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2025-02-25T19:12:49.464353003Z"
    description: A Helm chart for ohdsi's atlas and webapi deployments.
    digest: 22e83912c76689cf13b0c86afd0ea98047a96fead988ac8b433d6b45db2420e5
    name: ohdsi
    type: application
    urls:
    - https://raw.githubusercontent.com/mdaca/ohdsi-helm/main/chart/ohdsi/ohdsi-0.1.6.tgz
    version: 0.1.6
generated: "2025-02-25T19:12:49.462966424Z"
