apiVersion: v1
entries:
  ohdsi:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2024-11-18T23:48:06.436852892Z"
    description: A Helm chart for ohdsi's atlas and webapi deployments.
    digest: 8e63d3915a1cf7645dd22ee76f54113cc62f873753c1dc43dc681a51b6f022f4
    name: ohdsi
    type: application
    urls:
    - https://raw.githubusercontent.com/mdaca/ohdsi-helm/develop/chart/ohdsi/ohdsi-0.1.6.tgz
    version: 0.1.6
generated: "2024-11-18T23:48:06.435758145Z"
