apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ohdsi.fullname" . }}-cm0
  labels:
    io.kompose.service: atlas
  {{- include "ohdsi.labels" . | nindent 4 }}
  annotations:
    use-subpath: "true"
data:
  config-local.js: {{ .Values.cm0.configLocalJs | toYaml | indent 1 }}