apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas
  labels:
    app.kubernetes.io/name: atlas
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: ohdsi-atlas
  {{- include "ohdsi.labels" . | nindent 4 }}
  annotations:
    app.kubernetes.io/name: atlas
spec:
  replicas: {{ .Values.atlas.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: atlas
    {{- include "ohdsi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atlas
      {{- include "ohdsi.selectorLabels" . | nindent 8 }}
      annotations:
        app.kubernetes.io/name: atlas
    spec:
      imagePullSecrets:
      {{- toYaml .Values.atlas.imagePullSecrets | nindent 8 }}
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.atlas.atlas.image.repository }}:{{ .Values.atlas.atlas.image.tag }}
        imagePullPolicy: Always
        name: atlas
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /etc/atlas/config-local.js
          name: atlas-cm0
          subPath: config-local.js
        - mountPath: /etc/nginx/conf.d/default.conf
          name: atlas-cm0
          subPath: default.conf
      restartPolicy: Always
      volumes:
      - configMap:
          items:
          - key: config-local.js
            path: config-local.js
          - key: default.conf
            path: default.conf
          name: atlas-cm0
        name: atlas-cm0
