apiVersion: v1
kind: Service
metadata:
  name: atlas
  labels:
  {{- include "ohdsi.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: ../../kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
spec:
  type: {{ .Values.atlas.type }}
  selector:
    io.kompose.service: atlas
  {{- include "ohdsi.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.atlas.ports | toYaml | nindent 2 }}
