apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ohdsi.fullname" . }}-cm0
  labels:
    io.kompose.service: atlas
  {{- include "ohdsi.labels" . | nindent 4 }}
  annotations:
    use-subpath: "true"
data:
  config-local.js: {{ .Values.cm0.configLocalJs | toYaml | indent 1 }}
  nginx-default.conf: {{ .Values.cm0.nginx-default.conf | toYaml | indent 1}}
  30-atlas-env-subst.sh: {{ .Values.cm0.30-atlas-env-subst.sh | toYaml | indent 1 }}
