apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas
  labels:
    io.kompose.service: atlas
  {{- include "ohdsi.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: ../../kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
spec:
  replicas: {{ .Values.atlas.replicas }}
  selector:
    matchLabels:
      io.kompose.service: atlas
    {{- include "ohdsi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.service: atlas
      {{- include "ohdsi.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: ../../kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
    spec:
      imagePullSecrets:
      {{- toYaml .Values.atlas.imagePullSecrets | nindent 8 }}
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.atlas.atlas.image.repository }}:{{ .Values.atlas.atlas.image.tag }}
        imagePullPolicy: Always
        name: atlas
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /etc/atlas/config-local.js
          name: atlas-cm0
          subPath: config-local.js
        - mountPath: /etc/nginx/conf.d/default.conf
          name: atlas-cm0
          subPath: default.conf
        - mountPath: /docker-entrypoint.d/30-atlas-env-subst.sh
          name: atlas-cm0
          subPath: 30-atlas-env-subst.sh
      restartPolicy: Always
      volumes:
      - configMap:
          items:
          - key: config-local.js
            path: config-local.js
          - key: default.conf
            path: default.conf
          - key: 30-atlas-env-subst.sh
            path: 30-atlas-env-subst.sh
          name: atlas-cm0
        name: atlas-cm0
