# Web API Secrets
apiVersion: v1
kind: Secret
metadata:
  name: webapi-secrets
  labels:
    {{- include "ohdsi.labels" . | nindent 4 }}
data:
  FLYWAY_DATASOURCE_PASSWORD: {{ .Values.webapiSecrets.flywayDatasourcePassword | b64enc }}
  FLYWAY_DATASOURCE_USERNAME: {{ .Values.webapiSecrets.flywayDatasourceUsername | b64enc }}
  OID_APISECRET: {{ .Values.webapiSecrets.oidApisecret | b64enc }}
  TRUSTSTORE_PASSWORD: {{ .Values.webapiSecrets.truststorePassword | b64enc }}
  WEBAPI_DATASOURCE_PASSWORD: {{ .Values.webapiSecrets.webapiDatasourcePassword | b64enc }}
  WEBAPI_DATASOURCE_USERNAME: {{ .Values.webapiSecrets.webapiDatasourceUsername | b64enc }}
  ohdsi.p12: {{ .Values.webapiSecrets.ohdsiP12 }}
type: Opaque
