# TLS Secret
apiVersion: v1
kind: Secret
metadata:
  name: ohdsi-tls-secret
  labels:
    app.kubernetes.io/managed-by: {{ .Values.ohdsiTlsSecret.labels.managedBy }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.ohdsiTlsSecret.annotations.releaseName }}
    meta.helm.sh/release-namespace: {{ .Values.ohdsiTlsSecret.annotations.releaseNamespace }}
data:
  tls.crt: {{ .Values.ohdsiTlsSecret.tlsCrt | quote }}
  tls.key: {{ .Values.ohdsiTlsSecret.tlsKey | quote }}
type: kubernetes.io/tls

---

# Web API Secrets
apiVersion: v1
kind: Secret
metadata:
  name: webapi-secrets
  labels:
    {{- include "ohdsi.labels" . | nindent 4 }}
data:
  FLYWAY_DATASOURCE_USERNAME: {{ .Values.webapiSecrets.flywayDatasourceUsername | b64enc }}
  OID_APISECRET: {{ .Values.webapiSecrets.oidApisecret | b64enc }}
  TRUSTSTORE_PASSWORD: {{ .Values.webapiSecrets.truststorePassword | b64enc }}
  WEBAPI_DATASOURCE_USERNAME: {{ .Values.webapiSecrets.webapiDatasourceUsername | b64enc  }}
type: Opaque
