# TLS Secret
apiVersion: v1
kind: Secret
metadata:
  name: ohdsi-tls-secret
  labels:
    app.kubernetes.io/name: ohdsi-tls-secret
    app.kubernetes.io/part-of: ohdsi
    app.kubernetes.io/component: tls
  annotations:
    description: "TLS Secret for securing OHDSI communications"
data:
  tls.crt: {{ .Values.ohdsiTlsSecret.tlsCrt }}
  tls.key: {{ .Values.ohdsiTlsSecret.tlsKey }}
type: kubernetes.io/tls

---

# Web API Secrets
apiVersion: v1
kind: Secret
metadata:
  name: webapi-secrets
  labels:
    {{- include "ohdsi.labels" . | nindent 4 }}
data:
  FLYWAY_DATASOURCE_PASSWORD: {{ .Values.webapiSecrets.flywayDatasourcePassword | b64enc }}
  FLYWAY_DATASOURCE_USERNAME: {{ .Values.webapiSecrets.flywayDatasourceUsername | b64enc }}
  OID_APISECRET: {{ .Values.webapiSecrets.oidApisecret | b64enc }}
  TRUSTSTORE_PASSWORD: {{ .Values.webapiSecrets.truststorePassword | b64enc }}
  WEBAPI_DATASOURCE_PASSWORD: {{ .Values.webapiSecrets.webapiDatasourcePassword | b64enc }}
  WEBAPI_DATASOURCE_USERNAME: {{ .Values.webapiSecrets.webapiDatasourceUsername | b64enc }}
  ohdsi.p12: {{ .Values.webapiSecrets.ohdsiP12 | quote }}
type: Opaque
