apiVersion: v1
kind: Secret
metadata:
  name: ohdsi-tls-secret
  labels:
    app.kubernetes.io/managed-by: {{ .Values.ohdsiTlsSecret.labels.managedBy }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.ohdsiTlsSecret.annotations.releaseName }}
    meta.helm.sh/release-namespace: {{ .Values.ohdsiTlsSecret.annotations.releaseNamespace }}
data:
  tls.crt: {{ .Values.ohdsiTlsSecret.tlsCrt | quote }}
  tls.key: {{ .Values.ohdsiTlsSecret.tlsKey | quote }}
type: kubernetes.io/tls
