apiVersion: v1
kind: Secret
metadata:
  name: webapi-secrets
  labels:
  {{- include "ohdsi.labels" . | nindent 4 }}
data:
  FLYWAY_DATASOURCE_PASSWORD: {{ .Values.webapiSecrets.flywayDatasourcePassword }}
  FLYWAY_DATASOURCE_USERNAME: {{ .Values.webapiSecrets.flywayDatasourceUsername }}
  OID_APISECRET: {{ .Values.webapiSecrets.oidApisecret }}
  TRUSTSTORE_PASSWORD: {{ .Values.webapiSecrets.truststorePassword }}
  WEBAPI_DATASOURCE_PASSWORD: {{ .Values.webapiSecrets.webapiDatasourcePassword }}
  WEBAPI_DATASOURCE_USERNAME: {{ .Values.webapiSecrets.webapiDatasourceUsername }}
  ohdsi.p12: {{ .Values.webapiSecrets.ohdsiP12 }}
type: Opaque
