apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohdsi.fullname" . }}-webapi-p12-secret
  labels:
  {{- include "ohdsi.labels" . | nindent 4 }}
data:
  ohdsi-p12: {{ .Values.webapiP12Secret.ohdsiP12 | b64enc | quote }}
  ohdsi-p12-password: {{ .Values.webapiP12Secret.ohdsiP12Password | b64enc | quote }}
  tls.crt: {{ .Values.ohdsiTlsSecret.tlsCrt | b64enc | quote }}
  tls.key: {{ .Values.ohdsiTlsSecret.tlsKey | b64enc | quote }}
type: kubernetes.io/tls