apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohdsi.fullname" . }}-webapi-p12-secret
  labels:
  {{- include "ohdsi.labels" . | nindent 4 }}
data:
  ohdsi-p12: {{ required "webapiP12Secret.ohdsiP12 is required" .Values.webapiP12Secret.ohdsiP12
    | b64enc | quote }}
  ohdsi-p12-password: {{ required "webapiP12Secret.ohdsiP12Password is required"
    .Values.webapiP12Secret.ohdsiP12Password | b64enc | quote }}
  tls.crt: {{ required "ohdsiTlsSecret.tlsCrt is required" .Values.ohdsiTlsSecret.tlsCrt
    | b64enc | quote }}
  tls.key: {{ required "ohdsiTlsSecret.tlsKey is required" .Values.ohdsiTlsSecret.tlsKey
    | b64enc | quote }}
type: kubernetes.io/tls