apiVersion: v1
kind: Service
metadata:
  name: {{ include "ohdsi.fullname" . }}-webapi
  labels:
    io.kompose.service: webapi
  {{- include "ohdsi.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: ../../kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
spec:
  type: {{ .Values.webapi.type }}
  selector:
    io.kompose.service: webapi
  {{- include "ohdsi.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webapi.ports | toYaml | nindent 2 }}