apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohdsi.fullname" . }}-webapi-secrets
  labels:
  {{- include "ohdsi.labels" . | nindent 4 }}
data:
  FLYWAY_DATASOURCE_PASSWORD: {{ required "webapiSecrets.flywayDatasourcePassword is required" .Values.webapiSecrets.flywayDatasourcePassword | b64dec | b64enc | quote }}
  FLYWAY_DATASOURCE_USERNAME: {{ required "webapiSecrets.flywayDatasourceUsername is required" .Values.webapiSecrets.flywayDatasourceUsername | b64dec | b64enc | quote }}
  OID_APISECRET: {{ required "webapiSecrets.oidApisecret is required" .Values.webapiSecrets.oidApisecret | b64dec | b64enc | quote }}
  TRUSTSTORE_PASSWORD: {{ required "webapiSecrets.truststorePassword is required" .Values.webapiSecrets.truststorePassword | b64dec | b64enc | quote }}
  WEBAPI_DATASOURCE_PASSWORD: {{ required "webapiSecrets.webapiDatasourcePassword is required" .Values.webapiSecrets.webapiDatasourcePassword | b64dec | b64enc | quote }}
  WEBAPI_DATASOURCE_USERNAME: {{ required "webapiSecrets.webapiDatasourceUsername is required" .Values.webapiSecrets.webapiDatasourceUsername | b64dec | b64enc | quote }}
  ohdsi.p12: {{ required "webapiSecrets.ohdsiP12 is required" .Values.webapiSecrets.ohdsiP12 | b64dec | b64enc | quote }}
type: Opaque